### PR TITLE
Fixed bug where rack array parameters weren't encoded

### PR DESCRIPTION
**Pull request by hspearman**
This fix will help us out on LP, where we're having issues with unencoded URL params.

### CODE REVIEW

**Comment by hspearman** [comment]
Do we want to increment versions in this repo? Is there anything special we need to do to make sure LP-UI can grab the latest?

**Comment by ebenoist** [comment]
@hspearman I imagine we're pushing these changes to npm directly from local at this point. So you'll want to increment the package.json and run an npm publish

**Comment by hspearman** [comment]
[Facets with ampersands in them break things because the internet is a terrible place and I no longer want to work in it](https://trello.com/c/Ii7FdNLS/2077-facets-with-ampersands-in-them-break-things-because-the-internet-is-a-terrible-place-and-i-no-longer-want-to-work-in-it)

**Comment by ebenoist** [comment]
👍

**Pull request merged**
